2025-03-02 14:51:24,658 INFO    MainThread:351221 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-02 14:51:24,658 INFO    MainThread:351221 [wandb_setup.py:_flush():67] Configure stats pid to 351221
2025-03-02 14:51:24,658 INFO    MainThread:351221 [wandb_setup.py:_flush():67] Loading settings from /home/sumit/.config/wandb/settings
2025-03-02 14:51:24,658 INFO    MainThread:351221 [wandb_setup.py:_flush():67] Loading settings from /media/sumit/dd6174bf-2d05-4a68-9324-d66b0a8e63762/Aditi/MERL-ICML2024/pretrain/wandb/settings
2025-03-02 14:51:24,658 INFO    MainThread:351221 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-02 14:51:24,658 INFO    MainThread:351221 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /media/sumit/dd6174bf-2d05-4a68-9324-d66b0a8e63762/Aditi/MERL-ICML2024/pretrain/wandb/offline-run-20250302_145124-wm854fr5/logs/debug.log
2025-03-02 14:51:24,659 INFO    MainThread:351221 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /media/sumit/dd6174bf-2d05-4a68-9324-d66b0a8e63762/Aditi/MERL-ICML2024/pretrain/wandb/offline-run-20250302_145124-wm854fr5/logs/debug-internal.log
2025-03-02 14:51:24,659 INFO    MainThread:351221 [wandb_init.py:init():761] calling init triggers
2025-03-02 14:51:24,659 INFO    MainThread:351221 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'total_epochs': 20, 'weight_decay': 1e-08, 'ecg_model': 'vit_tiny', 'text_model': 'ncbi/MedCPT-Query-Encoder', 'batch_size': 128, 'val_zeroshot': 'all_sets', 'prompt_type': 'CKEPE', '_wandb': {}}
2025-03-02 14:51:24,659 INFO    MainThread:351221 [wandb_init.py:init():784] starting backend
2025-03-02 14:51:24,659 INFO    MainThread:351221 [wandb_init.py:init():788] sending inform_init request
2025-03-02 14:51:24,665 INFO    MainThread:351221 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-02 14:51:24,666 INFO    MainThread:351221 [wandb_init.py:init():803] backend started and connected
2025-03-02 14:51:24,669 INFO    MainThread:351221 [wandb_init.py:init():896] updated telemetry
2025-03-02 14:51:24,678 INFO    MainThread:351221 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-02 14:51:24,790 INFO    MainThread:351221 [wandb_init.py:init():995] starting run threads in backend
2025-03-02 14:51:25,002 INFO    MainThread:351221 [wandb_run.py:_console_start():2377] atexit reg
2025-03-02 14:51:25,003 INFO    MainThread:351221 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-02 14:51:25,003 INFO    MainThread:351221 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-02 14:51:25,004 INFO    MainThread:351221 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-02 14:51:25,008 INFO    MainThread:351221 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-02 14:54:18,812 WARNING MsgRouterThr:351221 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/media/sumit/dd6174bf-2d05-4a68-9324-d66b0a8e63762/Aditi/aditi/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/sumit/dd6174bf-2d05-4a68-9324-d66b0a8e63762/Aditi/aditi/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/sumit/dd6174bf-2d05-4a68-9324-d66b0a8e63762/Aditi/aditi/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/sumit/dd6174bf-2d05-4a68-9324-d66b0a8e63762/Aditi/aditi/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/media/sumit/dd6174bf-2d05-4a68-9324-d66b0a8e63762/Aditi/aditi/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-02 14:54:18,814 INFO    MsgRouterThr:351221 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
